version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: Hearvo/run.py
      SETTING: "dev"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hearvo_dev
      PYTHONUNBUFFERED: 0

  postgres:
    container_name: db_postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hearvo_dev
    volumes:
      - db_volume:/var/lib/postgresql/
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 1s
    #   timeout: 2s
    #   retries: 10


volumes:
  db_volume: