version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run
      ENVIRONMENT: "dev"
      DEBUG: "True"
      SECRET_KEY: aaaabbbbcccc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hearvo_dev
      PYTHONUNBUFFERED: 0

    volumes:
      - ./Hearvo:/app/Hearvo
      - ./migrations:/app/migrations
      - ./run.py:/app/run.py
    

  postgres:
    container_name: db_postgres
    image: postgres:13.0
    restart: always
    ports:
      - "6432:5432"
    expose:
      - '6432'
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: db_postgres
        POSTGRES_PORT: 5432
        POSTGRES_DB: hearvo_dev
    volumes:
      - db_volume:/var/lib/postgresql/


volumes:
  db_volume: