"""empty message

Revision ID: 4780e00d19d7
Revises: aa9985ae2525
Create Date: 2021-02-13 22:17:07.081982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4780e00d19d7'
down_revision = 'aa9985ae2525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('gender_detail', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'gender_detail')
    # ### end Alembic commands ###
