"""empty message

Revision ID: 53ae442d3171
Revises: f13eaef7b7e1
Create Date: 2021-02-16 15:18:05.747503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ae442d3171'
down_revision = 'f13eaef7b7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
