"""empty message

Revision ID: c33f53011403
Revises: 3db67d82cb15
Create Date: 2020-11-14 13:35:56.995177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33f53011403'
down_revision = '3db67d82cb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_select_user', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vote_select_user', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote_select_user', type_='foreignkey')
    op.drop_column('vote_select_user', 'post_id')
    # ### end Alembic commands ###
