"""empty message

Revision ID: d69e851b3f80
Revises: 53ae442d3171
Create Date: 2021-02-16 15:29:37.119080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69e851b3f80'
down_revision = '53ae442d3171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'group', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'country_id')
    # ### end Alembic commands ###
