"""empty message

Revision ID: f13eaef7b7e1
Revises: 4780e00d19d7
Create Date: 2021-02-15 19:55:22.754707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13eaef7b7e1'
down_revision = '4780e00d19d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mj_option', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('mj_option_lang_id_fkey', 'mj_option', type_='foreignkey')
    op.create_foreign_key(None, 'mj_option', 'country', ['country_id'], ['id'])
    op.drop_column('mj_option', 'lang_id')
    op.add_column('post', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('post_lang_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'country', ['country_id'], ['id'])
    op.drop_column('post', 'lang_id')
    op.add_column('topic', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('topic_lang_id_fkey', 'topic', type_='foreignkey')
    op.create_foreign_key(None, 'topic', 'country', ['country_id'], ['id'])
    op.drop_column('topic', 'lang_id')
    op.add_column('user_info', sa.Column('country_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('user_info_lang_id_fkey', 'user_info', type_='foreignkey')
    op.create_foreign_key(None, 'user_info', 'country', ['country_id'], ['id'])
    op.drop_column('user_info', 'lang_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('lang_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.create_foreign_key('user_info_lang_id_fkey', 'user_info', 'lang', ['lang_id'], ['id'])
    op.drop_column('user_info', 'country_id')
    op.add_column('topic', sa.Column('lang_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.create_foreign_key('topic_lang_id_fkey', 'topic', 'lang', ['lang_id'], ['id'])
    op.drop_column('topic', 'country_id')
    op.add_column('post', sa.Column('lang_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_lang_id_fkey', 'post', 'lang', ['lang_id'], ['id'])
    op.drop_column('post', 'country_id')
    op.add_column('mj_option', sa.Column('lang_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mj_option', type_='foreignkey')
    op.create_foreign_key('mj_option_lang_id_fkey', 'mj_option', 'lang', ['lang_id'], ['id'])
    op.drop_column('mj_option', 'country_id')
    # ### end Alembic commands ###
