"""empty message

Revision ID: f718762f04b5
Revises: 
Create Date: 2021-06-19 17:38:53.170498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f718762f04b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('num_comment', sa.BigInteger(), nullable=True),
    sa.Column('num_vote', sa.BigInteger(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('vote_type_id', sa.BigInteger(), nullable=False),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('current_post_detail_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['current_post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['vote_type_id'], ['vote_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_detail',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num_vote', sa.BigInteger(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('google_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=350), nullable=True),
    sa.Column('google_email', sa.String(length=350), nullable=True),
    sa.Column('deleted_email', sa.String(length=350), nullable=True),
    sa.Column('hashed_password', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vote_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vote_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mj_option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('post_detail_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('num_of_posts', sa.BigInteger(), nullable=True),
    sa.Column('num_of_users', sa.BigInteger(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('string_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.BigInteger(), nullable=True),
    sa.Column('gender_detail', sa.String(length=20), nullable=True),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('birth_year', sa.BigInteger(), nullable=True),
    sa.Column('login_count', sa.BigInteger(), nullable=True),
    sa.Column('hide_realname', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('string_id')
    )
    op.create_table('vote_mj',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('mj_type', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('post_detail_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_select',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('post_detail_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('num_of_good', sa.BigInteger(), nullable=True),
    sa.Column('num_of_bad', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('num_of_users', sa.BigInteger(), nullable=True),
    sa.Column('num_of_posts', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_topic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info_following',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('following_user_info_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['following_user_info_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info_post_voted',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('vote_type_id', sa.BigInteger(), nullable=False),
    sa.Column('post_detail_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['vote_type_id'], ['vote_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info_topic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_mj_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('vote_mj_id', sa.BigInteger(), nullable=False),
    sa.Column('mj_option_id', sa.BigInteger(), nullable=False),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['mj_option_id'], ['mj_option.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['vote_mj_id'], ['vote_mj.id'], ),
    sa.PrimaryKeyConstraint('vote_mj_id', 'mj_option_id', 'user_info_id', 'post_id')
    )
    op.create_table('vote_select_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('vote_select_id', sa.BigInteger(), nullable=False),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('post_detail_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_detail_id'], ['post_detail.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['vote_select_id'], ['vote_select.id'], ),
    sa.PrimaryKeyConstraint('vote_select_id', 'user_info_id', 'post_id')
    )
    op.create_table('comment_fav',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('good_or_bad', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_info_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_reason',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('reason_detail', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_reason')
    op.drop_table('user_info_group')
    op.drop_table('report')
    op.drop_table('post_group')
    op.drop_table('comment_fav')
    op.drop_table('vote_select_user')
    op.drop_table('vote_mj_user')
    op.drop_table('user_info_topic')
    op.drop_table('user_info_post_voted')
    op.drop_table('user_info_following')
    op.drop_table('post_topic')
    op.drop_table('group')
    op.drop_table('comment')
    op.drop_table('vote_select')
    op.drop_table('vote_mj')
    op.drop_table('user_info')
    op.drop_table('topic')
    op.drop_table('mj_option')
    op.drop_table('vote_type')
    op.drop_table('user')
    op.drop_table('post_detail')
    op.drop_table('post')
    op.drop_table('country')
    # ### end Alembic commands ###
